version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-blue-leaf-a2kgv5zf.eu-central-1.pg.koyeb.app:5432/koyebdb?sslmode=require
      SPRING_DATASOURCE_USERNAME: koyeb-adm
      SPRING_DATASOURCE_PASSWORD: npg_KQVgG8oYOU7W
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker